name: sa
channels:
- conda-forge
dependencies:
- python=3.7  # keep at python 3.7
- numpy=1.18.1
- pandas=1.0.3
- matplotlib=3.2.1
- jupyter=1.0.0
- jupyterlab=2.0.1
- scipy=1.4.1
- scikit-learn=0.22.1
- pyprojroot=0.2.0
- ipykernel=5.2.0
- seaborn=0.10.0
- pytest=5.4.1
- nltk=3.5
- pip  # don't pin this version, we always want latest
- pip:
  - -e src/.  # this installs your custom package in development mode.
 